sudo: required
services:
  - docker


script:
  - docker-compose build
  - docker-compose up

before_deploy:
  - docker login -u USERNAME -p USERPASSWORD

deploy:
  provider: : script
  script: docker push thomasgravy/dokerTest
  on:
    branch: origin
