app:
  container_name: express-project-appnote
  restart: always
  build: .
  ports:
    - "3000:3000"
  links:
    - mongo

mongo:
  container_name: mongo
  image: mongo
  expose:
    - "27017"
  volumes:
    - ./data:/data/db
  ports:
    - "27017:27017"
